### ISSUE TITLE
stacktrace

### ISSUE THREAD

**Issue by MarcelH-Tabeo** [nikolaydubina/smrcptr#4]
I get this:
```
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
        panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x2 addr=0x0 pc=0x100a19cf4]

goroutine 29 [running]:
go/types.(*Checker).handleBailout(0x1400047a200, 0x140009c1be8)
        /usr/local/go/src/go/types/check.go:367 +0x9c
panic({0x100beece0?, 0x100defce0?})
        /usr/local/go/src/runtime/panic.go:770 +0x124
go/types.(*StdSizes).Sizeof(0x0, {0x100c44188, 0x100df3840})
        /usr/local/go/src/go/types/sizes.go:228 +0x314
go/types.(*Config).sizeof(...)
        /usr/local/go/src/go/types/sizes.go:333
go/types.representableConst.func1({0x100c44188?, 0x100df3840?})
        /usr/local/go/src/go/types/const.go:76 +0x9c
go/types.representableConst({0x100c45488, 0x100de8660}, 0x1400047a200, 0x100df3840, 0x140009bf428)
        /usr/local/go/src/go/types/const.go:92 +0x138
go/types.(*Checker).representation(0x1400047a200, 0x14000883ec0, 0x100df3840)
        /usr/local/go/src/go/types/const.go:256 +0x68
go/types.(*Checker).implicitTypeAndValue(0x1400047a200, 0x14000883ec0, {0x100c44188, 0x100df3840})
        /usr/local/go/src/go/types/expr.go:375 +0x304
go/types.(*Checker).convertUntyped(0x1400047a200, 0x14000883ec0, {0x100c44188, 0x100df3840})
        /usr/local/go/src/go/types/const.go:289 +0x30
go/types.(*Checker).matchTypes(0x1400047a200, 0x14000883e40, 0x14000883ec0)
        /usr/local/go/src/go/types/expr.go:926 +0x7c
go/types.(*Checker).binary(0x1400047a200, 0x14000883e40, {0x100c44a78, 0x14000a047e0}, {0x100c44aa8, 0x14000a6d340}, {0x100c44f88, 0x14000365180}, 0x29, 0x12e0b0b)
        /usr/local/go/src/go/types/expr.go:800 +0x114
go/types.(*Checker).exprInternal(0x1400047a200, 0x0, 0x14000883e40, {0x100c44a78, 0x14000a047e0}, {0x0, 0x0})
        /usr/local/go/src/go/types/expr.go:1416 +0x1d4
go/types.(*Checker).rawExpr(0x1400047a200, 0x0, 0x14000883e40, {0x100c44a78?, 0x14000a047e0?}, {0x0?, 0x0?}, 0x0)
        /usr/local/go/src/go/types/expr.go:979 +0x12c
go/types.(*Checker).expr(0x1400047a200, 0x0?, 0x14000883e40, {0x100c44a78?, 0x14000a047e0?})
        /usr/local/go/src/go/types/expr.go:1513 +0x38
go/types.(*Checker).binary(0x1400047a200, 0x14000883e40, {0x100c44a78, 0x14000a04870}, {0x100c44a78, 0x14000a047e0}, {0x100c44a78, 0x14000a04840}, 0x22, 0x12e0b0f)
        /usr/local/go/src/go/types/expr.go:783 +0x70
go/types.(*Checker).exprInternal(0x1400047a200, 0x0, 0x14000883e40, {0x100c44a78, 0x14000a04870}, {0x0, 0x0})
        /usr/local/go/src/go/types/expr.go:1416 +0x1d4
go/types.(*Checker).rawExpr(0x1400047a200, 0x0, 0x14000883e40, {0x100c44a78?, 0x14000a04870?}, {0x0?, 0x0?}, 0x0)
        /usr/local/go/src/go/types/expr.go:979 +0x12c
go/types.(*Checker).expr(0x1400047a200, 0x100c43d88?, 0x14000883e40, {0x100c44a78?, 0x14000a04870?})
        /usr/local/go/src/go/types/expr.go:1513 +0x38
go/types.(*Checker).stmt(0x1400047a200, 0x0, {0x100c44c28, 0x14000a6d3c0})
        /usr/local/go/src/go/types/stmt.go:570 +0xda4
go/types.(*Checker).stmtList(0x1400047a200, 0x0, {0x1400037e300?, 0x0?, 0x26?})
        /usr/local/go/src/go/types/stmt.go:121 +0x88
go/types.(*Checker).funcBody(0x1400047a200, 0x100c441d8?, {0x140003dc680?, 0x140000da1c0?}, 0x14000883600, 0x14000a049c0, {0x0?, 0x0?})
        /usr/local/go/src/go/types/stmt.go:41 +0x21c
go/types.(*Checker).funcDecl.func1()
        /usr/local/go/src/go/types/decl.go:852 +0x44
go/types.(*Checker).processDelayed(0x1400047a200, 0x0)
        /usr/local/go/src/go/types/check.go:467 +0x12c
go/types.(*Checker).checkFiles(0x1400047a200, {0x1400039efa0, 0x1, 0x1})
        /usr/local/go/src/go/types/check.go:411 +0x188
go/types.(*Checker).Files(...)
        /usr/local/go/src/go/types/check.go:372
golang.org/x/tools/go/packages.(*loader).loadPackage(0x1400010a000, 0x1400021c840)
        /Users/Marcello/go/pkg/mod/golang.org/x/tools@v0.3.0/go/packages/packages.go:1037 +0x784
golang.org/x/tools/go/packages.(*loader).loadRecursive.func1()
        /Users/Marcello/go/pkg/mod/golang.org/x/tools@v0.3.0/go/packages/packages.go:847 +0x178
sync.(*Once).doSlow(0x0?, 0x0?)
        /usr/local/go/src/sync/once.go:74 +0x100
sync.(*Once).Do(...)
        /usr/local/go/src/sync/once.go:65
golang.org/x/tools/go/packages.(*loader).loadRecursive(0x0?, 0x0?)
        /Users/Marcello/go/pkg/mod/golang.org/x/tools@v0.3.0/go/packages/packages.go:835 +0x50
golang.org/x/tools/go/packages.(*loader).refine.func2(0x0?)
        /Users/Marcello/go/pkg/mod/golang.org/x/tools@v0.3.0/go/packages/packages.go:770 +0x30
created by golang.org/x/tools/go/packages.(*loader).refine in goroutine 1
        /Users/Marcello/go/pkg/mod/golang.org/x/tools@v0.3.0/go/packages/packages.go:769 +0xaa4
```

**Comment by nikolaydubina** [comment]
this is nil pointer dereference. can you share code which you run this on?

need to bisect where this happens. ideally .go file or function that fails with this.

**Comment by MarcelH-Tabeo** [comment]
I think, you can find this yourself, because it's a public package: (so my log-dump)
golang.org/x/tools@v0.3.0/go/packages/packages.go:769

**Comment by nikolaydubina** [comment]
no. I can not see which package you are running from this stack trace.

all I see is that code from this linter is panicing when invoking go ast parser code.

besides. there is no runtime here. this code in principle can not report in stack trace symbol names about code that you are running it on, since it is not even compiled yet.

if it is private, no need to share. as I said, try to bisect where it happens. feel free to open PR with fix/example. cheers!

**Comment by MarcelH-Tabeo** [comment]
solved in the latest version !
